#!/usr/bin/env bash

pushd `dirname $0` > /dev/null
SCRIPT_DIR=`pwd -P`
popd > /dev/null

source $SCRIPT_DIR/common

cd $VELUM_DIR/kubernetes
./cleanup
# if there is a change in the templates (e.g. filename) this will leave
# the old manifests in place which leads to spawning unwanted pods
# so clean them up
rm -rf manifests/*
cd $SCRIPT_DIR
./stop_kubelet

# Cleanup kuberentes tmp directory because sometimes we face this:
# https://gihub.com/kubernetes/kubernetes/issues/38498
sudo rm -rf $VELUM_DIR/kubernetes/tmp/*
