#!/usr/bin/env bash

# http://stackoverflow.com/a/4774063
pushd `dirname $0` > /dev/null
ROOT_DIR=$(dirname `pwd -P`)
popd > /dev/null

CAASP_DEVENV_DIR=$ROOT_DIR/caasp-devenv
SALT_DIR=$ROOT_DIR/k8s-salt
TERRAFORM_DIR=$ROOT_DIR/k8s-terraform
VELUM_DIR=$ROOT_DIR/velum
CONTAINER_MANIFESTS_DIR=$ROOT_DIR/caasp-container-manifests

log()   { echo ">>> $1" ; }

# Usage: fetch_repo "my_repo_url", branch, "dir_name"
fetch_repo() {
  log 'Fetching '$1

  new_dir="$ROOT_DIR/$3"
  mkdir -p $3
  cd $3
  git init
  git remote add origin $1
  git fetch origin $2
  git reset --hard FETCH_HEAD
  cd $ROOT_DIR
}
