#!/usr/bin/env bash

# The first argument in this script is the number of minions to spawn.
# When TERRAFORM_BRANCH environment variable is defined, it is used as the
# branch to pull from k8s-terraform upstream repository. If is is not defined
# we use "master" by default.

SCRIPT_DIR="$(dirname $0)"
source $SCRIPT_DIR/common

LATEST_IMAGE="${LATEST_IMAGE:-true}"

if [ -z "${TERRAFORM_BRANCH+x}" ]; then
  branch=master
else
  branch=$TERRAFORM_BRANCH
fi

fetch_repo 'https://github.com/kubic-project/terraform.git' $branch $TERRAFORM_DIR

cd $TERRAFORM_DIR

SALT_PATH=$SALT_DIR PREFIX=e2e_tests SKIP_DASHBOARD=1 FLAVOUR=caasp MINIONS_SIZE=$1 LATEST_IMAGE=$LATEST_IMAGE timeout 15m contrib/libvirt/k8s-libvirt.sh apply
